apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaiubuggywebapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kaiubuggywebapp
  template:
    metadata:
      labels:
        app: kaiubuggywebapp
    spec:
      containers:
      - name: kaiubuggywebapp
        image: 718795354116.dkr.ecr.us-east-1.amazonaws.com/asg
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kaiubuggywebapp
    k8s-app: kaiubuggywebapp
  name: kaiubuggywebapp
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: kaiubuggywebapp
